version: '3.9'
services:
  postgres:
    image: '$DB_IMAGE'
    ports:
      - '$DB_ACCESS_PORT:$DB_INTERNAL_PORT'
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
