version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: '$DB_USER'
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  # nextjs:
  #   image: node:20.17-alpine
  #   ports:
  #     - 3000:3000
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: $DB_INTERNAL_PORT
  #     DB_USER: $DB_USER
  #     DB_PASSWORD: $DB_PASSWORD
  #     DB_NAME: $DB_NAME
  #   volumes:
  #     - ./nextjs:/app
  #     - /app/node_modules
  #   depends_on:
  #     - postgres
